#!/usr/bin/env python3
"""Deploy the SeedSigner Python app + embit onto the P4's internal-flash VFS
over a single held-open serial connection, then optionally run an import-smoke
or boot the Controller.

Unlike the SD card (where a soft-reset clears the mount, forcing one-connection
operation — see sd_format_push.py), the internal-flash FAT VFS persists across
resets, so this is a plain push. We still reuse the held-connection raw-REPL
primitives for speed and a definitive liveness check.

Layout written to the device (no sys.path edits needed — device sys.path already
includes '/lib'):

    /lib/seedsigner/...   <- src/seedsigner/ (minus resources/ unless --resources)
    /lib/embit/...        <- embit/src/embit/

Modes:
    --mode push-only      push source, touch nothing else (default)
    --mode import-smoke    push, then `import seedsigner.controller` on-device and
                           report success / full traceback (no reset, no main.py)
    --mode run            push, write /main.py that calls Controller.start(), reset

    python3 tools/deploy_app.py [--mode import-smoke] [--clean] [--port /dev/ttyACM0]
"""
import argparse
import base64
import os
import sys

# Reuse the proven raw-REPL primitives from the SD pusher.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sd_format_push import hard_reset_and_wait, raw_exec  # noqa: E402

PORT = "/dev/ttyACM0"
SS_SRC = "/home/kdmukai/dev/seedsigner/src/seedsigner"
EMBIT_SRC = "/home/kdmukai/dev/embit/src/embit"
SS_DST = "/lib/seedsigner"
EMBIT_DST = "/lib/embit"

# micropython-lib stdlib modules the import closure needs but stock firmware
# lacks. This list IS the set the production firmware must freeze into its
# manifest (the "required frozen packages"); vendoring to /lib is the no-reflash
# dev equivalent. Each is a single-module package: <name>/<name>.py.
MPY_LIB_STDLIB = ("/home/kdmukai/dev/seedsigner-micropython-builder/deps/micropython/"
                  "upstream/lib/micropython-lib/python-stdlib")
STDLIB_DEPS = ["logging", "hmac"]

# Dev stopgap: a top-level `secp256k1` module. embit on MicroPython does a bare
# `import secp256k1` (expecting the native C module); this re-exports embit's
# pure-Python fallback so the app imports without that firmware module. Slow for
# real signing — production builds the native secp256k1 C module into firmware.
SECP256K1_SHIM = (
    "# Dev stopgap (tools/deploy_app.py): top-level secp256k1 = embit's\n"
    "# pure-Python EC fallback. Production = native secp256k1 C module in firmware.\n"
    "from embit.util.py_secp256k1 import *  # noqa\n"
)

# Device-side helpers, defined once in the REPL global namespace and reused
# across subsequent raw_exec calls (globals persist within one connection).
DEVICE_HELPERS = r"""
import os, binascii
def _mkdirp(p):
    cur = ''
    for x in p.strip('/').split('/'):
        cur += '/' + x
        try:
            os.mkdir(cur)
        except OSError:
            pass
def _rmrf(p):
    try:
        st = os.stat(p)
    except OSError:
        return
    if st[0] & 0x4000:
        for e in os.listdir(p):
            _rmrf(p + '/' + e)
        os.rmdir(p)
    else:
        os.remove(p)
def _w(path, b64):
    f = open(path, 'wb'); f.write(binascii.a2b_base64(b64)); f.close()
def _wa(path, b64):
    f = open(path, 'ab'); f.write(binascii.a2b_base64(b64)); f.close()
def _ls(p):
    try:
        st = os.stat(p)
    except OSError:
        return
    if st[0] & 0x4000:
        for e in os.listdir(p):
            _ls(p + '/' + e)
    else:
        print(p, st[6])
print('helpers ready')
"""

IMPORT_SMOKE = r"""
import sys
# Pop the app + its FS-vendored deps so an edited file recompiles. Must include
# the top-level vendored modules (secp256k1 shim, logging, hmac): if only
# embit.* is popped, the cached secp256k1 shim keeps stale function references
# to the previous py_secp256k1 and the re-import silently runs old code.
for _m in list(sys.modules):
    if _m.split('.')[0] in ('seedsigner', 'embit', 'secp256k1', 'logging', 'hmac'):
        del sys.modules[_m]
try:
    import seedsigner.controller
    print('SMOKE_OK')
except Exception as _e:
    sys.print_exception(_e)
    print('SMOKE_FAIL')
"""

MAIN_PY = """\
# Auto-generated by tools/deploy_app.py --mode run. SeedSigner app entry.
import sys
try:
    from seedsigner.controller import Controller
    Controller.get_instance().start()
except Exception as e:
    sys.print_exception(e)
    print('[main] Controller exited via exception; dropping to REPL.')
"""


def _push_big(ser, b64, remote, chunk=10000):
    """A file whose base64 exceeds one batch: stream it in append chunks."""
    off, first = 0, True
    while off < len(b64):
        part = b64[off:off + chunk]
        fn = "_w" if first else "_wa"
        raw_exec(ser, "%s('%s','%s')" % (fn, remote, part), timeout=60)
        off += len(part)
        first = False


def push_bytes(ser, data, remote, batch_bytes=18000):
    b64 = base64.b64encode(data).decode()
    if len(b64) > batch_bytes:
        _push_big(ser, b64, remote)
    else:
        raw_exec(ser, "_w('%s','%s')" % (remote, b64), timeout=60)


def ensure_dev_deps(ser):
    """Vendor the micropython-lib stdlib modules + secp256k1 dev shim to /lib.
    Cheap and idempotent; keeps import-smoke/run self-contained without a reflash."""
    for name in STDLIB_DEPS:
        src = os.path.join(MPY_LIB_STDLIB, name, name + ".py")
        if not os.path.exists(src):
            print("[vendor] WARN micropython-lib module not found:", name)
            continue
        push_bytes(ser, open(src, "rb").read(), "/lib/%s.py" % name)
        print("[vendor] /lib/%s.py" % name)
    push_bytes(ser, SECP256K1_SHIM.encode(), "/lib/secp256k1.py")
    print("[vendor] /lib/secp256k1.py (dev shim)")


def push_tree(ser, local_root, remote_root, label, excl_dirs, excl_suffix,
              expected, on_dev=None, force=False, batch_bytes=18000):
    """Collect the tree, mkdir -p all dirs in few calls, then write files in
    batched raw_exec payloads (the per-call REPL handshake dominates, so packing
    many small files per call is the win). Records expected sizes into `expected`
    for a single post-pass verification."""
    files, dirs = [], set()
    for dirpath, dirnames, filenames in os.walk(local_root):
        dirnames[:] = [d for d in dirnames if d not in excl_dirs]
        rel = os.path.relpath(dirpath, local_root)
        rdir = remote_root if rel == "." else remote_root + "/" + rel.replace(os.sep, "/")
        dirs.add(rdir)
        for f in filenames:
            if any(f.endswith(s) for s in excl_suffix):
                continue
            files.append((os.path.join(dirpath, f), rdir + "/" + f))

    # Create directories (batch the _mkdirp calls).
    mk, acc = [], 0
    for d in sorted(dirs):
        call = "_mkdirp('%s')" % d
        if acc + len(call) > batch_bytes:
            raw_exec(ser, "\n".join(mk)); mk, acc = [], 0
        mk.append(call); acc += len(call) + 1
    if mk:
        raw_exec(ser, "\n".join(mk))

    state = {"batch": [], "cur": 0, "pushed": 0}
    count = total = skipped = 0

    def flush():
        if state["batch"]:
            raw_exec(ser, "\n".join(state["batch"]), timeout=90)
            state["pushed"] += len(state["batch"])
            state["batch"].clear()
            state["cur"] = 0
            print("[push] %-9s %d files written ..." % (label, state["pushed"]), flush=True)

    for lp, rp in sorted(files):
        data = open(lp, "rb").read()
        expected[rp] = len(data)
        count += 1
        total += len(data)
        if not force and on_dev is not None and on_dev.get(rp) == len(data):
            skipped += 1
            continue  # unchanged on device (size match) — skip for fast iteration
        b64 = base64.b64encode(data).decode()
        if len(b64) > batch_bytes:
            flush()
            _push_big(ser, b64, rp)
            state["pushed"] += 1
            continue
        if state["cur"] + len(b64) > batch_bytes:
            flush()
        state["batch"].append("_w('%s','%s')" % (rp, b64))
        state["cur"] += len(b64)
    flush()
    print("[push] %-9s done: %d files (%d pushed, %d unchanged), %d bytes"
          % (label, count, count - skipped, skipped, total), flush=True)
    return count, total


def device_tree(ser):
    """One recursive os.stat pass; returns {path: size} for both dst roots."""
    out = raw_exec(ser, "_ls('%s'); _ls('%s'); print('LS_END')" % (SS_DST, EMBIT_DST),
                   timeout=30)
    on_dev = {}
    for line in out.splitlines():
        line = line.strip()
        if not line or line == "LS_END":
            continue
        try:
            path, sz = line.rsplit(" ", 1)
            on_dev[path] = int(sz)
        except ValueError:
            pass
    return on_dev


def verify(ser, expected):
    on_dev = device_tree(ser)
    missing = [p for p in expected if p not in on_dev]
    mismatch = [(p, expected[p], on_dev[p]) for p in expected
                if p in on_dev and on_dev[p] != expected[p]]
    extra = [p for p in on_dev if p not in expected]
    print("[verify] device has %d files; expected %d; missing %d; size-mismatch %d; extra %d"
          % (len(on_dev), len(expected), len(missing), len(mismatch), len(extra)))
    for p in missing[:20]:
        print("  MISSING ", p)
    for p, e, g in mismatch[:20]:
        print("  MISMATCH", p, "expected", e, "got", g)
    return not missing and not mismatch


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", default=PORT)
    ap.add_argument("--mode", default="push-only",
                    choices=["push-only", "import-smoke", "run", "smoke-only"])
    ap.add_argument("--clean", action="store_true",
                    help="recursively remove /lib/seedsigner and /lib/embit first")
    ap.add_argument("--force", action="store_true",
                    help="re-push every file even if its size matches the device")
    ap.add_argument("--resources", action="store_true",
                    help="also push src/seedsigner/resources (25MB; skipped by default)")
    args = ap.parse_args()

    print("[deploy] poll-opening REPL (no hard reset) ...")
    ser = hard_reset_and_wait(args.port, do_reset=False)
    try:
        raw_exec(ser, DEVICE_HELPERS)

        # smoke-only: don't push the app tree, just (re-)vendor deps + import test.
        if args.mode == "smoke-only":
            print("[deploy] smoke-only: vendor deps + import seedsigner.controller ...")
            ensure_dev_deps(ser)
            out = raw_exec(ser, IMPORT_SMOKE, timeout=60)
            print("---- device output ----\n%s\n-----------------------" % out)
            print("[deploy] RESULT:", "PASS" if "SMOKE_OK" in out else "FAIL")
            return

        if args.clean:
            print("[deploy] cleaning %s and %s ..." % (SS_DST, EMBIT_DST))
            raw_exec(ser, "_rmrf('%s'); _rmrf('%s'); print('cleaned')" % (SS_DST, EMBIT_DST))

        # Incremental: pull the device tree once so unchanged files are skipped.
        on_dev = {} if args.clean else device_tree(ser)
        ss_excl = {"__pycache__"} if args.resources else {"__pycache__", "resources"}
        expected = {}
        push_tree(ser, SS_SRC, SS_DST, "seedsigner", ss_excl, (".pyc",),
                  expected, on_dev, args.force)
        push_tree(ser, EMBIT_SRC, EMBIT_DST, "embit", {"__pycache__"}, (".pyc",),
                  expected, on_dev, args.force)
        ok = verify(ser, expected)
        print("[deploy] verify:", "PASS" if ok else "FAIL")
        ensure_dev_deps(ser)

        if args.mode == "import-smoke":
            print("[deploy] running import smoke: import seedsigner.controller ...")
            out = raw_exec(ser, IMPORT_SMOKE, timeout=60)
            print("---- device output ----")
            print(out)
            print("-----------------------")
            print("[deploy] RESULT:", "PASS" if "SMOKE_OK" in out else "FAIL")
        elif args.mode == "run":
            print("[deploy] writing /main.py and resetting to boot Controller ...")
            b64 = base64.b64encode(MAIN_PY.encode()).decode()
            raw_exec(ser, "_f=open('/main.py','wb'); _f.write(binascii.a2b_base64('%s')); "
                          "_f.close(); print('main.py written')" % b64)
    finally:
        ser.close()
    print("[deploy] done.")


if __name__ == "__main__":
    main()
