#!/usr/bin/env python3
"""Make the ESP32-P4 default-boot into the interactive i18n locale tester.

Writes the tester (tools/esp_i18n_locale_test.py) to the device flash as /main.py
(MicroPython auto-runs boot.py then main.py at startup), wrapping the entry call so a
failure prints the traceback and drops to the REPL rather than boot-looping. The file
is sent base64 in small chunks (the raw REPL drops bytes on a multi-KB single paste),
each written with an explicit close, and the final size is verified before reset.

    python3 tools/set_p4_boot_tester.py
"""
import base64
import os
import sys
import time

sys.path.insert(0, os.path.dirname(__file__))
from sd_format_push import hard_reset_and_wait, raw_exec

TESTER = os.path.join(os.path.dirname(__file__), "esp_i18n_locale_test.py")

src = open(TESTER, "r", encoding="utf-8").read().rstrip()
assert src.endswith("main()"), "tester no longer ends with main(); update this script"
body = src[: -len("main()")].rstrip()
mainpy = body + (
    "\n\n"
    "# --- P4 boot entry (auto-generated by tools/set_p4_boot_tester.py) ---\n"
    "# Run the interactive locale tester on boot; on any error print it and fall to\n"
    "# the REPL so the dev board stays recoverable over serial (no boot-loop).\n"
    "try:\n"
    "    main()\n"
    "except Exception as _e:\n"
    "    import sys as _sys\n"
    "    _sys.print_exception(_e)\n"
)
raw = mainpy.encode("utf-8")
b64 = base64.b64encode(raw).decode("ascii")
CHUNK = 512  # multiple of 4 so each chunk is independently valid base64


def main():
    ser = hard_reset_and_wait("/dev/ttyACM0")
    print(raw_exec(ser, "import ubinascii, os", timeout=10).strip())
    for i in range(0, len(b64), CHUNK):
        chunk = b64[i:i + CHUNK]
        mode = "wb" if i == 0 else "ab"
        code = "with open('main.py','%s') as f: f.write(ubinascii.a2b_base64(%r))" % (mode, chunk)
        raw_exec(ser, code, timeout=15)
    out = raw_exec(ser, "print(os.stat('main.py')[6], os.listdir('/'))", timeout=10).strip()
    print("after write:", out)
    size = int(out.split()[0])
    if size != len(raw):
        print("ERROR: /main.py is %d bytes, expected %d — NOT resetting." % (size, len(raw)))
        return
    print("OK: /main.py = %d bytes (matches). Resetting to boot into the tester..." % size)
    ser.write(b"\r\x03\x03import machine; machine.reset()\r")
    time.sleep(1)


main()
