#!/usr/bin/env python3
"""Stage the SeedSigner app + embit into <repo>/frozen_app for the frozen build.

Replaces the old hand-staging of `frozen_app/` (gitignored, untooled) with a
deterministic, repeatable step. Run on the HOST before `make docker-build-all`
(the Docker build mounts only this repo, so the app/embit siblings must be
mirrored in first). `make docker-build-all` depends on `make stage-app`, so a
normal build auto-stages; run `make stage-app` directly to (re)stage without
building.

What it does:
  1. Resolve the app + embit sources via tools/_devenv (env/.env-overridable; no
     hard-coded paths). Local dev uses the sibling working trees; CI points these
     at the pinned deps/seedsigner + deps/embit submodules.
  2. Clean-mirror `seedsigner/` and `embit/` into frozen_app/ (excluding
     resources/, __pycache__/, *.pyc), deleting stale files so removed modules
     don't linger in the freeze.
  3. Determine the version (env-var override -> app git fallback) and bake it into
     frozen_app/seedsigner/_version.py (auto-frozen by the manifest's
     package("seedsigner")). See tools/_version_bake.py.
  4. Regenerate the provenance marker frozen_app/seedsigner_frozen_build.py
     (SHAs, dirty count, build time, board) -- the on-device proof of what was baked.

Usage:
    python3 tools/stage_frozen_app.py [--board BOARD]
    SEEDSIGNER_VERSION=v9.9.9 python3 tools/stage_frozen_app.py   # version override
"""
import argparse
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _devenv        # noqa: E402  (env-driven paths; no hard-coded /home/... in committed files)
import _version_bake  # noqa: E402

FROZEN_ROOT = os.path.join(_devenv.REPO_ROOT, "frozen_app")
MARKER_NAME = "seedsigner_frozen_build.py"

# Excludes, mirroring tools/deploy_app.py's device push: seedsigner drops its
# ~25MB resources/ (data, never imported -> stays on the microSD) plus bytecode
# caches; embit keeps everything but the caches.
SS_IGNORE = shutil.ignore_patterns("__pycache__", "resources", "*.pyc")
EMBIT_IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc")


def _die(msg):
    sys.exit("[stage] ERROR: " + msg)


def _git(repo, *args):
    """Run `git -C repo ...`, returning stripped stdout or None on any failure."""
    try:
        out = subprocess.run(["git", "-C", repo, *args],
                             capture_output=True, text=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    return out.stdout.strip()


def _short_sha(repo):
    return _git(repo, "rev-parse", "--short", "HEAD") or "unknown"


def _dirty_count(repo, pathspec=None):
    """Number of uncommitted (tracked or untracked) paths -- how far the mirrored
    tree differs from the recorded SHA. Scoped to `pathspec` (the baked package
    subtree) so repo-level scratch outside the freeze doesn't inflate the count.
    Warn but never refuse on a dirty tree."""
    args = ["status", "--porcelain"]
    if pathspec:
        args += ["--", pathspec]
    out = _git(repo, *args)
    if out is None:
        return 0
    return len([ln for ln in out.splitlines() if ln.strip()])


def _mirror(src, dst, ignore, label):
    """Clean-mirror `src` -> `dst`: wipe dst, then copy src minus `ignore`. The
    wipe is the `--delete` -- no stale module can survive from a prior stage."""
    if not os.path.isdir(src):
        _die("%s source not found: %s\n"
             "       Set $SS_APP_DIR / $SS_EMBIT_DIR (or .env) to point at the app "
             "and embit checkouts." % (label, src))
    if os.path.isdir(dst):
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=ignore)
    n = sum(len(files) for _, _, files in os.walk(dst))
    print("[stage] %-10s %s -> %s (%d files)" % (label, src, dst, n))


def _write_marker(path, fields):
    lines = [
        '"""Frozen-build marker: identifies the app tree baked into this firmware.',
        "",
        "Importable only when the frozen manifest included the app -- its presence (and",
        "these values) prove the device is running frozen code rather than /lib.",
        "Auto-generated by tools/stage_frozen_app.py; do not edit by hand.",
        '"""',
        'SEEDSIGNER_SHA = "%s"' % fields["SEEDSIGNER_SHA"],
        "SEEDSIGNER_DIRTY_FILES = %d" % fields["SEEDSIGNER_DIRTY_FILES"],
        'EMBIT_SHA = "%s"' % fields["EMBIT_SHA"],
        'BUILDER_SHA = "%s"' % fields["BUILDER_SHA"],
        'BUILT_UTC = "%s"' % fields["BUILT_UTC"],
        'BOARD = "%s"' % fields["BOARD"],
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--board", default=os.environ.get("BOARD", "UNKNOWN"),
                    help="board name recorded in the provenance marker "
                         "(default: $BOARD or UNKNOWN)")
    args = ap.parse_args()

    ss_src = _devenv.SS_SRC          # $SS_APP_DIR/src/seedsigner
    embit_src = _devenv.EMBIT_SRC    # $SS_EMBIT_DIR/src/embit
    app_dir = _devenv.SS_APP_DIR     # app repo root (git cwd for the version fallback)
    src_root = _devenv.SS_SRC_ROOT   # $SS_APP_DIR/src   (PYTHONPATH for the version fallback)
    embit_dir = _devenv.SS_EMBIT_DIR

    ss_dst = os.path.join(FROZEN_ROOT, "seedsigner")
    embit_dst = os.path.join(FROZEN_ROOT, "embit")

    print("[stage] app source:   %s" % ss_src)
    print("[stage] embit source: %s" % embit_src)
    os.makedirs(FROZEN_ROOT, exist_ok=True)

    # 1-2. Clean-mirror both packages.
    _mirror(ss_src, ss_dst, SS_IGNORE, "seedsigner")
    _mirror(embit_src, embit_dst, EMBIT_IGNORE, "embit")

    # 3. Determine + bake the version (AFTER the mirror so it survives the wipe).
    version, source = _version_bake.resolve_version(app_dir, src_root)
    vpath = _version_bake.write_version_module(ss_dst, version)
    print("[stage] version (%s): %s  ->  %s"
          % (source, version.get(_version_bake.KEY_NAME), vpath))

    # 4. Regenerate the provenance marker. Scope the app dirty count to the baked
    # package subtree (e.g. src/seedsigner), not the whole app repo.
    ss_pathspec = os.path.relpath(ss_src, app_dir)
    ss_dirty = _dirty_count(app_dir, ss_pathspec)
    if ss_dirty:
        print("[stage] WARN: baked package has %d uncommitted path(s) under %s; "
              "baking it anyway." % (ss_dirty, ss_pathspec))
    fields = {
        "SEEDSIGNER_SHA": _short_sha(app_dir),
        "SEEDSIGNER_DIRTY_FILES": ss_dirty,
        "EMBIT_SHA": _short_sha(embit_dir),
        "BUILDER_SHA": _short_sha(_devenv.REPO_ROOT),
        "BUILT_UTC": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "BOARD": args.board,
    }
    marker_path = os.path.join(FROZEN_ROOT, MARKER_NAME)
    _write_marker(marker_path, fields)
    print("[stage] provenance: %s (app %s%s, embit %s, builder %s, board %s)"
          % (marker_path, fields["SEEDSIGNER_SHA"],
             ("+%d dirty" % ss_dirty) if ss_dirty else "",
             fields["EMBIT_SHA"], fields["BUILDER_SHA"], fields["BOARD"]))
    print("[stage] done. frozen_app/ ready to freeze.")


if __name__ == "__main__":
    main()
